// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nazLgTEW7V6FTXLkGvtboX
// Component: W5L3j2c_1JJ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: mY87X3S2UUL/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Tilt from "@plasmicpkgs/react-parallax-tilt"; // plasmic-import: PfY466VIuq/codeComponent

import { useScreenVariants as useScreenVariantszpgDFsEUbio } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: __zpgDFsEUbio/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_red_panda_media_website.module.css"; // plasmic-import: nazLgTEW7V6FTXLkGvtboX/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: W5L3j2c_1JJ/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: -8WdXkfhmn7/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: gCQki7ZDykM/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 20vkZ39fVK/icon
import BrandInstagramsvgIcon from "./icons/PlasmicIcon__BrandInstagramsvg"; // plasmic-import: FPnuh-tu2Q/icon
import NetworksvgIcon from "./icons/PlasmicIcon__Networksvg"; // plasmic-import: cIibErcHe4/icon
import TanksvgIcon from "./icons/PlasmicIcon__Tanksvg"; // plasmic-import: 6DJUZbx4tI/icon
import BrandYoutubesvgIcon from "./icons/PlasmicIcon__BrandYoutubesvg"; // plasmic-import: 2IVwYszBQg/icon

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<"div">;
  button?: p.Flex<"button">;
  button2?: p.Flex<typeof Button2>;
};

export interface DefaultAboutUsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszpgDFsEUbio()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            hasGap={true}
            className={classNames(projectcss.all, sty.navBar)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__eCte)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tbodm)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"343px" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                src={{
                  src: "/plasmic/red_panda_media_website/images/rpsLogopng.png",
                  fullWidth: 1266,
                  fullHeight: 269,
                  aspectRatio: undefined
                }}
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___3CXsg)}
              >
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___5QhzX
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                  title={"Home" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qes7W
                    )}
                  >
                    {"Home"}
                  </div>
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__iJk1
                  )}
                  component={Link}
                  href={`/about`}
                  platform={"nextjs"}
                  title={"About Us" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b6Ezz
                    )}
                  >
                    {"About Us"}
                  </div>
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__d4WlX
                  )}
                  component={Link}
                  href={`/comics`}
                  platform={"nextjs"}
                  target={undefined}
                  title={"Comics" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bkskC
                    )}
                  >
                    {"Comics"}
                  </div>
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__xDhrm
                  )}
                  component={Link}
                  href={`/newsletter`}
                  platform={"nextjs"}
                  title={"Newsletter" as const}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w8Nd
                    )}
                  >
                    {"Newsletter"}
                  </div>
                </p.PlasmicLink>
              </p.Stack>

              {false ? (
                <div className={classNames(projectcss.all, sty.freeBox__bRpKk)}>
                  <button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Sign up"}
                  </button>

                  {true ? (
                    <Button2
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      className={classNames("__wab_instance", sty.button2)}
                      color={"clear" as const}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__bfAgG)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6Pe6N
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jsSo5
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button2>
                  ) : null}
                </div>
              ) : null}
            </p.Stack>
          </p.Stack>

          <div className={classNames(projectcss.all, sty.columns__wdoUr)}>
            <div className={classNames(projectcss.all, sty.column___8Y4Xl)}>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___5K5Y)}
                  direction={"left" as const}
                  effect={"bounce" as const}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qLKv7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zAeYn
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F47D31" }}
                        >
                          {"About Us"}
                        </span>
                      </React.Fragment>
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___0VlF)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("153px" as const)
                          : ("auto" as const)
                      }
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("100%" as const)
                          : ("475px" as const)
                      }
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/red_panda_media_website/images/_2905750293968504622481645286919988603550449Njpg.jpeg",
                        fullWidth: 750,
                        fullHeight: 563,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sPgZn
                      )}
                    >
                      {
                        "Each member of Red Panda Studios has unique skills and talents to bring to the group! We aim to highlight small artists and creators like ourselves online."
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vatbe
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#F47D31" }}
                        >
                          {"Company Motto"}
                        </span>
                      </React.Fragment>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lrCu3
                      )}
                    >
                      {
                        '"We do this not because it is easy, but because we thought it would be easy."\n-Anonymous'
                      }
                    </div>
                  </div>
                </Reveal>
              ) : null}
            </div>

            <div className={classNames(projectcss.all, sty.column__wESyh)}>
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gtT84)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <Reveal
                      className={classNames("__wab_instance", sty.reveal__imuZ)}
                      damping={0.5 as const}
                      direction={"up" as const}
                      duration={1000 as const}
                      effect={"bounce" as const}
                      reverse={false}
                      triggerOnce={true}
                    >
                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <Tilt
                          className={classNames(
                            "__wab_instance",
                            sty.tilt___5Y6S
                          )}
                          glareEnable={true}
                          tiltReverse={true}
                        >
                          {true ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__uuKR
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__anFih
                                )}
                              >
                                {"RPM Identification Card "}
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.columns__zecWl
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.column__wT5Ja
                                  )}
                                >
                                  <p.PlasmicImg
                                    alt={""}
                                    className={classNames(sty.img__v0N8F)}
                                    displayHeight={"116px" as const}
                                    displayMaxHeight={"none" as const}
                                    displayMaxWidth={"100%" as const}
                                    displayMinHeight={"0" as const}
                                    displayMinWidth={"0" as const}
                                    displayWidth={"119px" as const}
                                    loading={"lazy" as const}
                                    src={{
                                      src: "/plasmic/red_panda_media_website/images/disukopng.png",
                                      fullWidth: 3000,
                                      fullHeight: 3000,
                                      aspectRatio: undefined
                                    }}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__isHcz
                                    )}
                                  >
                                    {"FOUNDER"}
                                  </div>
                                </div>

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.column__p4Ew8
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__veho0
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>{""}</React.Fragment>
                                      {
                                        <h5
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.h5,
                                            projectcss.__wab_text,
                                            sty.h5__yvsFx
                                          )}
                                        >
                                          {"DISUKO A. MUSIC"}
                                        </h5>
                                      }
                                      <React.Fragment>
                                        {"1021 KAWAII ST.\nEARTH, PROBABLY"}
                                      </React.Fragment>
                                    </React.Fragment>
                                  </div>

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__uDvTb
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>{""}</React.Fragment>
                                      {
                                        <h5
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.h5,
                                            projectcss.__wab_text,
                                            sty.h5__xrK5U
                                          )}
                                        >
                                          {
                                            "Music Producer, 3D Artist, Designer, Content Creator"
                                          }
                                        </h5>
                                      }
                                      <React.Fragment>{""}</React.Fragment>
                                    </React.Fragment>
                                  </div>

                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__n2HsJ
                                    )}
                                  >
                                    <p.PlasmicLink
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.a,
                                        sty.link__sTn23
                                      )}
                                      component={Link}
                                      href={
                                        "https://twitter.com/disukomusic" as const
                                      }
                                      platform={"nextjs"}
                                      target={"_blank" as const}
                                    >
                                      <IconIcon
                                        className={classNames(
                                          projectcss.all,
                                          sty.svg__ujySn
                                        )}
                                        role={"img"}
                                      />
                                    </p.PlasmicLink>

                                    <p.PlasmicLink
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.a,
                                        sty.link__ncGo
                                      )}
                                      component={Link}
                                      href={
                                        "https://instagram.com/disukomusic" as const
                                      }
                                      platform={"nextjs"}
                                      target={"_blank" as const}
                                    >
                                      <BrandInstagramsvgIcon
                                        className={classNames(
                                          projectcss.all,
                                          sty.svg__ojIdu
                                        )}
                                        role={"img"}
                                      />
                                    </p.PlasmicLink>

                                    <p.PlasmicLink
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.a,
                                        sty.link__oMrBw
                                      )}
                                      component={Link}
                                      href={"https://disuko.gay" as const}
                                      platform={"nextjs"}
                                      target={"_blank" as const}
                                    >
                                      <NetworksvgIcon
                                        className={classNames(
                                          projectcss.all,
                                          sty.svg__im5Z
                                        )}
                                        role={"img"}
                                      />
                                    </p.PlasmicLink>
                                  </p.Stack>
                                </div>
                              </div>
                            </div>
                          ) : null}
                        </Tilt>
                      ) : null}

                      <Tilt
                        className={classNames(
                          "__wab_instance",
                          sty.tilt__jxIet
                        )}
                        glareEnable={true}
                        tiltEnable={true}
                        tiltReverse={true}
                      >
                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3O3Fq
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fwFTl
                              )}
                            >
                              {"RPM Identification Card "}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.columns__k4Y0J
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__jEnf9
                                )}
                              >
                                <p.PlasmicImg
                                  alt={""}
                                  className={classNames(sty.img__oFzi)}
                                  displayHeight={"116px" as const}
                                  displayMaxHeight={"none" as const}
                                  displayMaxWidth={"100%" as const}
                                  displayMinHeight={"0" as const}
                                  displayMinWidth={"0" as const}
                                  displayWidth={"119px" as const}
                                  loading={"lazy" as const}
                                  src={{
                                    src: "/plasmic/red_panda_media_website/images/redHeadshotjpg2.jpeg",
                                    fullWidth: 524,
                                    fullHeight: 524,
                                    aspectRatio: undefined
                                  }}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__lgj6Y
                                  )}
                                >
                                  {"FOUNDER"}
                                </div>
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__fuyEp
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___5AIxG
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__dS9Wg
                                        )}
                                      >
                                        {"VOID RED"}
                                      </h5>
                                    }
                                    <React.Fragment>
                                      {"829 B. GUNNI AVE\nMIDMERICA"}
                                    </React.Fragment>
                                  </React.Fragment>
                                </div>

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___63UzS
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__ig0Wf
                                        )}
                                      >
                                        {
                                          "Programmer, Music Producer, Content Creator"
                                        }
                                      </h5>
                                    }
                                    <React.Fragment>{""}</React.Fragment>
                                  </React.Fragment>
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__gyb6Y
                                  )}
                                >
                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__bVx1N
                                    )}
                                    component={Link}
                                    href={
                                      "https://twitter.com/Red_The_Music" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <IconIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__lReEw
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__m8Rzb
                                    )}
                                    component={Link}
                                    href={
                                      "https://voidreddev.newgrounds.com" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <TanksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__kzurH
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__euuxh
                                    )}
                                    component={Link}
                                    href={
                                      "https://www.youtube.com/@VoidRedDev" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <BrandYoutubesvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__ywwFp
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>
                                </p.Stack>
                              </div>
                            </div>
                          </div>
                        ) : null}
                      </Tilt>

                      <Tilt
                        className={classNames("__wab_instance", sty.tilt__kVXa)}
                        glareEnable={true}
                        tiltEnable={true}
                        tiltReverse={true}
                      >
                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__k9RiD
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vrt5X
                              )}
                            >
                              {"RPM Identification Card "}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.columns__vQn7K
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__nsj5P
                                )}
                              >
                                <p.PlasmicImg
                                  alt={""}
                                  className={classNames(sty.img__jgHx9)}
                                  displayHeight={"116px" as const}
                                  displayMaxHeight={"none" as const}
                                  displayMaxWidth={"100%" as const}
                                  displayMinHeight={"0" as const}
                                  displayMinWidth={"0" as const}
                                  displayWidth={"119px" as const}
                                  loading={"lazy" as const}
                                  src={{
                                    src: "/plasmic/red_panda_media_website/images/image20221126012705511Png.png",
                                    fullWidth: 88,
                                    fullHeight: 88,
                                    aspectRatio: undefined
                                  }}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__gvNbu
                                  )}
                                >
                                  {"PROGRAMMER"}
                                </div>
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__fkAal
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jti3W
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__qhmoL
                                        )}
                                      >
                                        {"MIDNIGHT SYNTAX"}
                                      </h5>
                                    }
                                    <React.Fragment>
                                      {"177013 N. HEN BLVD \nOHIO (HELL)"}
                                    </React.Fragment>
                                  </React.Fragment>
                                </div>

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__oh5Ll
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__h1Rvd
                                        )}
                                      >
                                        {
                                          "Programmer, Shader Artist, Sound Designer"
                                        }
                                      </h5>
                                    }
                                    <React.Fragment>{""}</React.Fragment>
                                  </React.Fragment>
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__qKtGb
                                  )}
                                >
                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__jOnX
                                    )}
                                    component={Link}
                                    href={
                                      "https://twitter.com/Midnight_Syntax" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <IconIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__kfW92
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__fHmJx
                                    )}
                                    component={Link}
                                    href={
                                      "https://midnightsyntax.newgrounds.com" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <TanksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__x6Ytm
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link___1KP2W
                                    )}
                                    component={Link}
                                    href={
                                      "https://www.youtube.com/channel/UCMOWF60TE-YJgu8gCal7zCA" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <BrandYoutubesvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg___4NzJr
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>
                                </p.Stack>
                              </div>
                            </div>
                          </div>
                        ) : null}
                      </Tilt>

                      <Tilt
                        className={classNames(
                          "__wab_instance",
                          sty.tilt___0LypT
                        )}
                        glareEnable={true}
                        tiltEnable={true}
                        tiltReverse={true}
                      >
                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___12KLm
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mLI5
                              )}
                            >
                              {"RPM Identification Card "}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.columns__mUkgU
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__ffxz4
                                )}
                              >
                                <p.PlasmicImg
                                  alt={""}
                                  className={classNames(sty.img__satTi)}
                                  displayHeight={"116px" as const}
                                  displayMaxHeight={"none" as const}
                                  displayMaxWidth={"100%" as const}
                                  displayMinHeight={"0" as const}
                                  displayMinWidth={"0" as const}
                                  displayWidth={"119px" as const}
                                  loading={"lazy" as const}
                                  src={{
                                    src: "/plasmic/red_panda_media_website/images/_0X9Headshotjpg2.jpeg",
                                    fullWidth: 512,
                                    fullHeight: 512,
                                    aspectRatio: undefined
                                  }}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__htIfK
                                  )}
                                >
                                  {"DESIGNER"}
                                </div>
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column___5KnDl
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ugyfr
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__x1FCh
                                        )}
                                      >
                                        {"0X9"}
                                      </h5>
                                    }
                                    <React.Fragment>
                                      {"727 W. YOOSEIT DR\nTRIANGULUM CLUSTER"}
                                    </React.Fragment>
                                  </React.Fragment>
                                </div>

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__uTfE
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h5
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h5,
                                          projectcss.__wab_text,
                                          sty.h5__o2Sxx
                                        )}
                                      >
                                        {
                                          "3D Artist, Game Designer, Content Creator"
                                        }
                                      </h5>
                                    }
                                    <React.Fragment>{""}</React.Fragment>
                                  </React.Fragment>
                                </div>

                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__fWt61
                                  )}
                                >
                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__bpDj
                                    )}
                                    component={Link}
                                    href={
                                      "https://www.instagram.com/0x9flips/" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <BrandInstagramsvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__zD5Qc
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link___8N1M8
                                    )}
                                    component={Link}
                                    href={"https://0x9.newgrounds.com" as const}
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <TanksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg___0Pf6Y
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>

                                  <p.PlasmicLink
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__mvULa
                                    )}
                                    component={Link}
                                    href={
                                      "https://www.youtube.com/channel/UCG7ABLntjhHaKVxvG2z4oHQ" as const
                                    }
                                    platform={"nextjs"}
                                    target={"_blank" as const}
                                  >
                                    <BrandYoutubesvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__nWxu
                                      )}
                                      role={"img"}
                                    />
                                  </p.PlasmicLink>
                                </p.Stack>
                              </div>
                            </div>
                          </div>
                        ) : null}
                      </Tilt>
                    </Reveal>
                  ) : null}
                </p.Stack>
              ) : null}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBar", "button", "button2"],
  navBar: ["navBar", "button", "button2"],
  button: ["button"],
  button2: ["button2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "div";
  button: "button";
  button2: typeof Button2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAboutUs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    button: makeNodeComponent("button"),
    button2: makeNodeComponent("button2"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "About Us🐾",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
